name: Main push deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: check
    runs-on: ${{ matrix.os }}
    concurrency:
      group: production-deploy
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          user: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          private_key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.PRODUCTION_SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; echo "Hello world"
